### ISSUE TITLE
HTML

### ISSUE THREAD

**Issue by Heber-Marcano** [TheBeeShow/prework-study-guide1#1]
# HTML

## User Story

As a bootcamp student

I want the prework notes to be structured on a webpage so that I can easily find and read information

## Acceptance Criteria

GIVEN a Prework Study Guide website WHEN I visit the website in my browser

THEN I see four boxes titled HTML, CSS, Git, and JavaScript with associated notes listed

**Comment by 786-aquib** [comment]
Hey, 
Cn u please tell me what will be the topic for your prework??
What should i add on ??

**Comment by Heber-Marcano** [comment]
I am about to do that today

**Comment by Heber-Marcano** [comment]
Are you my mentor?

**Comment by 786-aquib** [comment]
No, but i cn help you and it will help me also to get more familiar with github because i have just started so that ..

**Comment by Heber-Marcano** [comment]
what I do not understand is who are you?
